name: Minitest

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby: ["2.7", "3.0"]

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
